const express=require('express'),http=require('http'),{Server}=require('socket.io'),fs=require('fs'),path=require('path');
const app=express(),server=http.createServer(app),io=new Server(server),PORT=process.env.PORT||3000,DATA=path.join(__dirname,'data.json'),UP=path.join(__dirname,'public','uploads');fs.mkdirSync(UP,{recursive:true});
app.use(express.json({limit:'20mb'}));app.use(express.static(path.join(__dirname,'public')));let db={users:{},messages:[]};try{if(fs.existsSync(DATA))db=JSON.parse(fs.readFileSync(DATA))}catch{}const online=new Map(),clean=s=>String(s||'').trim().replace(/\s+/g,' ').slice(0,24),uid=()=>Math.random().toString(36).slice(2)+Date.now().toString(36),save=()=>{try{fs.writeFileSync(DATA,JSON.stringify(db))}catch{}},pub=u=>({username:u.username,avatar:u.avatar||'/bird.jpg',bio:u.bio||'',createdAt:u.createdAt});
app.post('/api/register',(q,r)=>{let n=clean(q.body.username),p=String(q.body.password||'');if(!n||p.length<4)return r.status(400).json({error:'Имя и пароль (минимум 4 символа) обязательны'});if(db.users[n])return r.status(409).json({error:'Такое имя уже занято'});db.users[n]={username:n,password:p,avatar:'/bird.jpg',bio:'',createdAt:Date.now()};save();r.json({user:pub(db.users[n])})});
app.post('/api/login',(q,r)=>{let n=clean(q.body.username),p=String(q.body.password||''),u=db.users[n];if(!u||u.password!==p)return r.status(401).json({error:'Неверное имя или пароль'});r.json({user:pub(u),messages:db.messages.slice(-2000)})});
app.post('/api/profile',(q,r)=>{let old=clean(q.body.username),u=db.users[old],next=clean(q.body.newUsername)||old;if(!u)return r.status(404).json({error:'Пользователь не найден'});if(next!==old&&db.users[next])return r.status(409).json({error:'Новое имя занято'});if(next!==old){u.username=next;db.users[next]=u;delete db.users[old];db.messages.forEach(m=>{if(m.from===old)m.from=next;if(m.to===old)m.to=next})}if(q.body.bio!==undefined)u.bio=String(q.body.bio).slice(0,160);if(q.body.avatar&&String(q.body.avatar).length<3e6)u.avatar=String(q.body.avatar);save();io.emit('userList',Object.values(db.users).map(pub));r.json({user:pub(u)})});
app.post('/api/upload',(q,r)=>{let n=clean(q.body.username),name=String(q.body.name||'file').replace(/[^a-zA-Z0-9._-]/g,'_').slice(0,100),data=String(q.body.data||'');if(!db.users[n]||!data.startsWith('data:'))return r.status(400).json({error:'Ошибка загрузки'});let m=data.match(/^data:([^;]+);base64,(.*)$/s);if(!m)return r.status(400).json({error:'Неверный файл'});let ext=(name.split('.').pop()||'bin').replace(/[^a-z0-9]/gi,'').slice(0,8)||'bin',f=uid()+'.'+ext;fs.writeFileSync(path.join(UP,f),Buffer.from(m[2],'base64'));r.json({url:'/uploads/'+f,type:m[1],name})});
app.get('*',(q,r)=>r.sendFile(path.join(__dirname,'public','index.html')));
io.on('connection',s=>{s.on('join',name=>{let u=db.users[clean(name)];if(!u)return;s.data.username=u.username;s.join('u:'+u.username);online.set(u.username,(online.get(u.username)||0)+1);s.emit('init',{me:pub(u),users:Object.values(db.users).map(pub),messages:db.messages.slice(-2000),online:[...online.keys()]});io.emit('presence',[...online.keys()])});s.on('privateMessage',p=>{let from=s.data.username,to=clean(p?.to),text=String(p?.text||'').trim().slice(0,4000);if(!from||!to||!text||!db.users[to])return;let m={id:uid(),from,to,text,time:Date.now(),kind:p.kind||'text',name:p.name||'',replyTo:p.replyTo||null};db.messages.push(m);db.messages=db.messages.slice(-10000);save();io.to('u:'+from).to('u:'+to).emit('privateMessage',m)});s.on('typing',p=>{if(s.data.username&&p?.to)io.to('u:'+clean(p.to)).emit('typing',{from:s.data.username,active:!!p.active})});s.on('deleteMessage',id=>{let m=db.messages.find(x=>x.id===id);if(!m||m.from!==s.data.username)return;db.messages=db.messages.filter(x=>x.id!==id);save();io.emit('messageDeleted',id)});s.on('disconnect',()=>{let u=s.data.username;if(!u)return;let n=(online.get(u)||1)-1;if(n<=0)online.delete(u);else online.set(u,n);io.emit('presence',[...online.keys()])})});server.listen(PORT,()=>console.log('NMX Messenger 3.0 on '+PORT));
